import type { ScorecardConfig } from "./types";

export const SCORECARD_DATA: ScorecardConfig = {
  weeks: ["3/30–4/05", "4/06–4/12", "4/13–4/19", "xx/xx–xx/xx", "xx/xx–xx/xx"],
  sections: [
    {
      id: "evergreen",
      title: "EVERGREEN METRICS",
      variant: "olive",
      rows: [
        {
          id: "commission-collected",
          metric: "Commission Collected",
          weeks: [
            { value: null },
            { value: "$125,195.50" },
            { value: "$131,423.64" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: "$115,155.73",
          metricType: null,
          monthlyActual: null,
          status: "green",
          metricOwner: "Jack",
          metricSource: "Hostaway",
          notes: null,
        },
        {
          id: "guest-experience-score",
          metric: "Guest Experience Score",
          weeks: [
            { value: "4.94" },
            { value: "4.89" },
            { value: "4.88" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: "green",
          metricOwner: "Christine",
          metricSource: null,
          notes: null,
        },
        {
          id: "live-property-count",
          metric: "Live Property Count",
          weeks: [
            { value: null },
            { value: "257" },
            { value: "261" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: null,
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
        {
          id: "properties-onboarding",
          metric: "Properties in Onboarding",
          weeks: [
            { value: null },
            { value: "15" },
            { value: "11" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: null,
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
      ],
    },
    {
      id: "sales",
      title: "SALES",
      variant: "blue",
      rows: [
        {
          id: "closed-deals",
          metric: "Closed Deals (Signed)",
          weeks: [
            { value: "2" },
            { value: "2" },
            { value: "2" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: "6.00",
          metricType: "Total",
          monthlyActual: null,
          status: "green",
          metricOwner: "Dennis",
          metricSource: null,
          notes: null,
        },
        {
          id: "meetings-booked-ads",
          metric: "Meetings Booked from Ads",
          weeks: [
            { value: "4" },
            { value: "5" },
            { value: "4" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: "green",
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
        {
          id: "leads-hyper-pursuit",
          metric: "Leads In Hyper Pursuit",
          weeks: [
            { value: "27" },
            { value: "25" },
            { value: "28" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: "green",
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
        {
          id: "contracts-sent",
          metric: "Contracts Sent",
          weeks: [
            { value: "4" },
            { value: "3" },
            { value: "2" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Total",
          monthlyActual: null,
          status: "green",
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
        {
          id: "meetings-sdr",
          metric: "Meetings Booked from SDR",
          weeks: [
            { value: null },
            { value: null },
            { value: "2" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: null,
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
      ],
    },
    {
      id: "marketing",
      title: "MARKETING",
      variant: "blue",
      rows: [
        {
          id: "meta-leads",
          metric: "Meta Leads",
          weeks: [
            { value: "3" },
            { value: "3" },
            { value: "4" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: "green",
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
        {
          id: "organic-website",
          metric: "Organic / Website",
          weeks: [
            { value: "1" },
            { value: "2" },
            { value: "2" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: "green",
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
      ],
    },
    {
      id: "account-management",
      title: "Account Management",
      variant: "red",
      rows: [
        {
          id: "av-response-time",
          metric: "Av. Response Time",
          weeks: [
            { value: "8.5" },
            { value: "8.6" },
            { value: "4.3" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "0.00",
          status: "green",
          metricOwner: "Summer",
          metricSource: null,
          notes: null,
        },
        {
          id: "notices-given",
          metric: "Notices Given",
          weeks: [
            { value: "3.00" },
            { value: "1.00" },
            { value: "1.00" },
            { value: "1.00" },
            { value: null },
          ],
          monthlyTarget: "6.00",
          metricType: "Total",
          monthlyActual: null,
          status: "yellow",
          metricOwner: "Summer",
          metricSource: null,
          notes: null,
        },
        {
          id: "offboarded",
          metric: "Offboarded",
          weeks: [
            { value: "0.00" },
            { value: "1.00" },
            { value: "0.00" },
            { value: "2.00" },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "0.75",
          status: "yellow",
          metricOwner: "Summer",
          metricSource: null,
          notes: null,
        },
      ],
    },
    {
      id: "guest-experience",
      title: "Guest Experience",
      variant: "red",
      rows: [
        {
          id: "review-score-all-otas",
          metric: "Overall Review Score (All OTAs)",
          weeks: [
            { value: "4.94" },
            { value: "4.89" },
            { value: "4.88" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "490.33%",
          status: "green",
          metricOwner: "Christine",
          metricSource: null,
          notes: null,
        },
        {
          id: "review-score-airbnb",
          metric: "Overall Review Score Airbnb",
          weeks: [
            { value: "5.00" },
            { value: "4.93" },
            { value: "4.87" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "493.33%",
          status: "green",
          metricOwner: "Christine",
          metricSource: "Airbnb",
          notes: null,
        },
        {
          id: "conversation-satisfaction",
          metric: "Conversation Satisfaction Rating (Guest)",
          weeks: [
            { value: "82.9%" },
            { value: "92.50%" },
            { value: "93.30%" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "92.90%",
          status: "green",
          metricOwner: "Christine",
          metricSource: "Conduit",
          notes: null,
        },
        {
          id: "automation-rate-guest",
          metric: "Automation Rate (Guest)",
          weeks: [
            { value: "94.20%" },
            { value: "92.50%" },
            { value: "93.20%" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "93.30%",
          status: "green",
          metricOwner: "Christine",
          metricSource: "Conduit",
          notes: null,
        },
      ],
    },
    {
      id: "revenue-management",
      title: "Revenue Management",
      variant: "red",
      rows: [
        {
          id: "revpar-0-30",
          metric: "Haven V. Market: Next 0-30 Day Performance. Average RevPar V. Market",
          weeks: [
            { value: "23.25%" },
            { value: "22.41%" },
            { value: "30.00%" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Total",
          monthlyActual: "75.66%",
          status: "green",
          metricOwner: "Tiff",
          metricSource: null,
          notes: null,
        },
        {
          id: "revpar-90",
          metric: "Haven V. Market: Next 90 Day Performance. Average RevPar V. Market",
          weeks: [
            { value: "12.64%" },
            { value: "13.92%" },
            { value: "20.22%" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "15.59%",
          status: "green",
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
        {
          id: "revpar-market-30",
          metric: "Haven Revpar vs Market Last 30 Days (Smokies Only)",
          weeks: [
            { value: "23.27%" },
            { value: "30.30%" },
            { value: "22.06%" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "25.21%",
          status: "green",
          metricOwner: null,
          metricSource: null,
          notes: null,
        },
      ],
    },
    {
      id: "accounting-finance",
      title: "ACCOUNTING / FINANCE",
      variant: "red",
      rows: [
        {
          id: "reservation-reconciliation",
          metric: "Weekly Reservation Reconciliation Discrepancy Rate (%)",
          weeks: [
            { value: "90%" },
            { value: "90%" },
            { value: "63%", note: "[1]" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: "95%",
          metricType: "Avg",
          monthlyActual: "81.00%",
          status: "green",
          metricOwner: "Jo",
          metricSource: "Clearing",
          notes: null,
        },
        {
          id: "vendor-payment-accuracy",
          metric: "Vendor Payment Accuracy Rate (%)",
          weeks: [
            { value: "99%" },
            { value: "99%" },
            { value: "98%", note: "[2]" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: "99%",
          metricType: "Avg",
          monthlyActual: "98.67%",
          status: "green",
          metricOwner: "Jo",
          metricSource: "Ramp",
          notes: null,
        },
        {
          id: "owner-statement-corrections",
          metric: "Owner Statements Related Corrections (#)",
          weeks: [
            { value: null },
            { value: null },
            { value: "1", note: "[3]" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: "<5",
          metricType: "Avg",
          monthlyActual: "1",
          status: "green",
          metricOwner: "Jo",
          metricSource: "Clearing",
          notes: null,
        },
        {
          id: "post-books-close",
          metric: "Post Books Close Adjustments (#)",
          weeks: [
            { value: null },
            { value: null },
            { value: "7", note: "[4]" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: "<10",
          metricType: "Total",
          monthlyActual: "7",
          status: "yellow",
          metricOwner: "Jo",
          metricSource: "BOOKS",
          notes: null,
        },
        {
          id: "damage-waivers-sold",
          metric: "Damage Waivers Sold",
          weeks: [
            { value: "$4,445" },
            { value: "$4,312" },
            { value: "$3,320" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: "Avg",
          monthlyActual: "402,566.87%",
          status: "green",
          metricOwner: "Christine",
          metricSource: "SuiteOp",
          notes: null,
        },
        {
          id: "early-check-ins",
          metric: "Early Check Ins",
          weeks: [
            { value: "$717" },
            { value: "$294" },
            { value: "$519" },
            { value: null },
            { value: null },
          ],
          monthlyTarget: null,
          metricType: null,
          monthlyActual: null,
          status: "green",
          metricOwner: "Christine",
          metricSource: "SuiteOp",
          notes: null,
        },
      ],
    },
  ],
};
